version: '3.3'
services:
  mysql:
    image: mysql:5.6
    ports:
      - "8005:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
  mysql8:
    image: mysql:8.0
    ports:
      - "8006:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
